version: '3.9'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pau:/var/lib/mysql
    ports:
      - 5433:5432
volumes:
  pau: